version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.11.0
        environment:
          NODE_ENV: test

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: sudo apt install -y postgresql-client || true

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

      - run: npm test
